spring:
    application:
        name: beaware
    datasource:
        url: jdbc:postgresql://localhost:5432/beaware
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: create
        database: POSTGRESQL
        show-sql: false
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    thymeleaf:
        cache: false
        enabled: true
        prefix: classpath:/static/templates/
        suffix: .html


server:
    servlet:
        session:
            cookie:
                http-only: true
    port: 8080

logging:
    level:
        be:
            aware:
                rest: debug
                service: debug
